---
- name: install mysql-client and dependencies
  apt:
    name: '{{ item }}'
    update_cache: yes
    cache_valid_time: 3600
    state: present
  with_items:
  - mysql-client
  - python-mysqldb

- name: download wp-cli
  get_url:
    url: 'https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar'
    dest: '/usr/local/bin/wp'
  tags: wordpress

- name: make wp-cli executable
  file:
    path: '/usr/local/bin/wp'
    mode: '0755'
  tags: wordpress

- name: check if wordpress is downloaded
  stat:
    path: '{{wordpress.dir}}/wp-load.php'
  register: wp_is_present
  tags: wordpress

- name: download wordpress
  command: wp core download --path='{{wordpress.dir}}' --allow-root
  when: wp_is_present.stat.exists == False
  tags: wordpress

- name: check if wp-config is present
  stat:
    path: '{{wordpress.dir}}/wp-config.php'
  register: wp_config_is_present
  tags: wordpress

- name: generate wp-config
  command: wp core config \
            --dbname='{{wordpress.db_name}}' \
            --dbuser='{{wordpress.db_user}}' \
            --dbpass='{{wordpress.db_pass}}' \
            --dbhost='{{wordpress.db_host}}' \
            --allow-root
  args:
    chdir: '{{wordpress.dir}}'
  when: wp_config_is_present.stat.exists == False
  register: wp_install
  tags: wordpress

- name: install wordpress
  command: wp core install \
            --url='http://{{ site.domain }}' \
            --title='{{ site.title }}' \
            --admin_user={{ wordpress.user }} \
            --admin_password={{ wordpress.pass }} \
            --admin_email={{ wordpress.email }} \
            --allow-root
  args:
    chdir: '{{wordpress.dir}}'
  when: wp_install.changed
  tags: wordpress

- name: remove wp-config-sample
  file:
    path: '{{ wordpress.dir }}/wp-config-sample.php'
    state: absent
  tags: wordpress
