---
- name: install php and its modules
  apt: pkg={{ item }} state=latest
  with_items:
    - php5
    - php5-cli
    - php5-curl
    - php5-gd
    - php5-imagick
    - php5-mysql
    - php5-xmlrpc
  notify: restart apache
  tags: php

- name: copy php.ini
  template:
    src: 'php.ini.j2'
    dest: '/etc/php5/apache2/php.ini'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: restart apache
  tags: php
